[versions]
junit = "5.7.1"
annotations = "26.0.1"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
publish = { id = "com.vanniktech.maven.publish", version = "0.32.0" }
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
